Repository academy-agents/academy, pull requests merged in 2025-05, with the labels that each got.

#84 Create docs site
  .github/workflows/check-docs.yml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  README.md
  academy/agent.py
  academy/behavior.py
  academy/event.py
  academy/exchange/http.py
  academy/exchange/proxystore.py
  academy/handle.py
  academy/manager.py
  academy/message.py
  docs/concepts.md
  docs/contributing/index.md
  docs/contributing/issues-pull-requests.md
  docs/contributing/releases.md
  docs/contributing/style-guide.md
  docs/css/extra.css
  docs/css/mkdocstrings.css
  docs/faq.md
  docs/generate_api.py
  docs/get-started.md
  docs/guides/example.md
  docs/guides/index.md
  docs/index.md
  docs/publications/index.md
  docs/static/architecture.jpg
  docs/static/favicon.png
  docs/templates/python/material/module.html.jinja
  mkdocs.yml
  pyproject.toml
  tests/agent_test.py
  tests/exchange/proxystore_test.py
  tests/message_test.py
Labels: development, documentation

#87 Add preprint to README
  README.md
Labels: documentation

#104 Add basic mailbox ownership model for `HttpExchange`
  academy/exchange/cloud/server.py
  tests/exchange/cloud/server_test.py
Labels: enhancement, exchange-v2

#108 Remove launcher protocol
  README.md
  academy/launcher.py
  academy/launcher/__init__.py
  academy/launcher/thread.py
  docs/concepts.md
  docs/get-started.md
  examples/01-actor-client/run-01.py
  examples/02-agent-loop/run-02.py
  examples/03-agent-agent/run-03.py
  examples/04-execution/run-04.py
  testing/fixture.py
  tests/handle_test.py
  tests/launcher/__init__.py
  tests/launcher/thread_test.py
  tests/launcher_test.py
  tests/manager_test.py
Labels: breaking

#112 Add mypy plugin to support inference on `Handle` attribute access
  academy/handle.py
  academy/mypy_plugin.py
  pyproject.toml
  tests/handle_test.py
  tests/mypy_plugin_test.py
Labels: enhancement
