Repository academy-agents/academy, pull requests merged in 2025-07, with the labels that each got.

#138 Add context pass through for action methods
  academy/agent.py
  academy/behavior.py
  academy/context.py
  academy/exchange/__init__.py
  academy/handle.py
  academy/manager.py
  tests/agent_test.py
  tests/behavior_test.py
  tests/context_test.py
  tests/exchange/client_test.py
  tests/handle_test.py
Labels: enhancement

#144 Warn when action-decorated method name clashes with protected handle method
  academy/behavior.py
  tests/behavior_test.py
Labels: enhancement

#141 Refactor exchange error message types
  academy/agent.py
  academy/exception.py
  academy/exchange/__init__.py
  academy/exchange/cloud/client.py
  academy/exchange/cloud/server.py
  academy/exchange/hybrid.py
  academy/exchange/local.py
  academy/exchange/redis.py
  academy/exchange/transport.py
  academy/handle.py
  academy/manager.py
  docs/concepts.md
  tests/exchange/cloud/client_test.py
  tests/exchange/cloud/server_test.py
  tests/exchange/transport_test.py
  tests/handle_test.py
Labels: breaking, internal

#145 Rename `Agent` to `Runtime` and `Behavior` to `Agent`
  README.md
  academy/agent.py
  academy/behavior.py
  academy/context.py
  academy/exception.py
  academy/exchange/__init__.py
  academy/exchange/cloud/client.py
  academy/exchange/cloud/server.py
  academy/exchange/hybrid.py
  academy/exchange/local.py
  academy/exchange/proxystore.py
  academy/exchange/redis.py
  academy/exchange/transport.py
  academy/handle.py
  academy/identifier.py
  academy/manager.py
  academy/mypy_plugin.py
  academy/runtime.py
  academy/state.py
  docs/concepts.md
  docs/faq.md
  docs/get-started.md
  examples/01-actor-client/run-01.py
  examples/02-agent-loop/run-02.py
  examples/03-agent-agent/run-03.py
  examples/04-execution/run-04.py
  testing/agents.py
  tests/agent_test.py
  tests/behavior_test.py
  tests/context_test.py
  tests/exchange/client_test.py
  tests/exchange/cloud/server_test.py
  tests/exchange/hybrid_test.py
  tests/exchange/proxystore_test.py
  tests/exchange/transport_test.py
  tests/handle_test.py
  tests/logging_test.py
  tests/manager_test.py
  tests/mypy_plugin_test.py
  tests/runtime_test.py
  tests/state_test.py
Labels: breaking

#148 Add migrating to v0.2 guide
  academy/agent.py
  docs/case-studies/index.md
  docs/guides/example.md
  docs/guides/index.md
  docs/guides/migrating-to-v0.2.md
  docs/publications/index.md
  mkdocs.yml
Labels: documentation

#149 Rename callbacks to `agent_on_{startup,shutdown}`
  academy/agent.py
  academy/exchange/cloud/client.py
  academy/exchange/hybrid.py
  academy/exchange/redis.py
  academy/runtime.py
  academy/state.py
  docs/concepts.md
  docs/faq.md
  docs/guides/migrating-to-v0.2.md
  examples/01-actor-client/run-01.py
  examples/02-agent-loop/run-02.py
  testing/agents.py
  tests/agent_test.py
  tests/manager_test.py
  tests/runtime_test.py
  tests/state_test.py
Labels: breaking

#150 Cancel running actions when an agent is shutdown
  academy/exception.py
  academy/runtime.py
  tests/runtime_test.py
Labels: enhancement

#151 Change terminate semantics to cancel pending requests
  academy/exception.py
  academy/exchange/cloud/server.py
  academy/exchange/hybrid.py
  academy/exchange/local.py
  academy/exchange/redis.py
  academy/exchange/transport.py
  pyproject.toml
  testing/redis.py
  tests/exchange/cloud/server_test.py
  tests/exchange/transport_test.py
Labels: bug

#156 Lazily deserialize arguments in `ActionRequest` messages
  academy/exchange/proxystore.py
  academy/message.py
  academy/runtime.py
  tests/exchange/proxystore_test.py
  tests/message_test.py
Labels: bug

#157 Fix issue in response result serialization
  academy/exchange/proxystore.py
  academy/handle.py
  academy/message.py
  tests/exchange/proxystore_test.py
  tests/message_test.py
  tests/runtime_test.py
Labels: bug

#159 Bump to Academy v0.2
  pyproject.toml
Labels: ignore-for-release, package

#161 Update contributing guide and templates
  .github/pull_request_template.md
  .github/release.yml
  docs/contributing/issues-pull-requests.md
  docs/contributing/releases.md
  docs/contributing/style-guide.md
Labels: documentation, build

#162 Add context manager support to `Runtime`
  academy/agent.py
  academy/exchange/__init__.py
  academy/manager.py
  academy/runtime.py
  docs/concepts.md
  tests/runtime_test.py
Labels: enhancement

#160 Refactor messages to use header/body model
  academy/exchange/__init__.py
  academy/exchange/cloud/client.py
  academy/exchange/cloud/server.py
  academy/exchange/hybrid.py
  academy/exchange/local.py
  academy/exchange/proxystore.py
  academy/exchange/redis.py
  academy/exchange/transport.py
  academy/handle.py
  academy/manager.py
  academy/message.py
  academy/runtime.py
  tests/unit/exchange/client_test.py
  tests/unit/exchange/cloud/server_test.py
  tests/unit/exchange/hybrid_test.py
  tests/unit/exchange/proxystore_test.py
  tests/unit/exchange/transport_test.py
  tests/unit/handle_test.py
  tests/unit/message_test.py
  tests/unit/runtime_test.py
Labels: refactor

#175 Add helper method for safely running sync functions within async actions
  academy/agent.py
  academy/context.py
  academy/event.py
  academy/runtime.py
  docs/faq.md
  tests/unit/agent_test.py
  tests/unit/event_test.py
Labels: enhancement

#179 Re-organization docs site
  .github/RELEASES.md
  .github/pull_request_template.md
  docs/best-practices.md
  docs/concepts/index.md
  docs/contributing.md
  docs/contributing/index.md
  docs/contributing/issues-pull-requests.md
  docs/contributing/style-guide.md
  docs/faq.md
  docs/guides/index.md
  docs/migration.md
  docs/version-policy.md
  mkdocs.yml
Labels: documentation

#182 Correct documentation aliases in version policy
  docs/version-policy.md
Labels: documentation

#181 Allow handles to be used by multiple clients
  academy/context.py
  academy/exception.py
  academy/exchange/__init__.py
  academy/handle.py
  academy/manager.py
  academy/runtime.py
  docs/migration.md
  examples/03-agent-agent/run-03.py
  testing/agents.py
  tests/integration/agent_agent_handles_test.py
  tests/unit/exchange/client_test.py
  tests/unit/handle_test.py
  tests/unit/runtime_test.py
Labels: breaking

#183 Consolidate Handle protocol with RemoteHandle
  academy/context.py
  academy/exception.py
  academy/exchange/__init__.py
  academy/handle.py
  academy/manager.py
  docs/get-started.md
  docs/migration.md
  tests/unit/exchange/client_test.py
  tests/unit/handle_test.py
  tests/unit/runtime_test.py
Labels: breaking

#188 Improve clarity of new docs additions
  academy/exchange/__init__.py
  academy/handle.py
  academy/runtime.py
  docs/get-started.md
  docs/migration.md
Labels: documentation

#195 Update .pre-commit-config.yaml configuration
  .pre-commit-config.yaml
Labels: build

#198 Fix flaky logging assertion in unit test
  academy/exchange/client.py
  tests/unit/exchange/client_test.py
  tests/unit/handle_test.py
Labels: test
